### PR TITLE
Switch sequence representation to u64

### LINKED ISSUE #46: Implement window 5-mer as a bitfield in a `u8`
I believe smafa's distance computation might be able to become significantly faster if each nucleotide is represented as a `u8`, where one of the lower 5 bits are set, instead of a `[bool; 5]`. The distance computation could then be done using an xor and a population count instruction, which will vectorize nicely.
A little more tricky, but even more efficient, would be to pack it into 4 bits per symbol, allowing 2 symbols per byte. However, that would change the distance computation where I'm not sure what the ideal is.

However, this would change the smafa database format.

I'm willing to give it a go if you're interested.

### PR DESCRIPTION
**Pull request by jakobnissen**
This PR is a rollup of several changes - you can review the individual commits (which are each fully functional and passes tests) if you want.

The major changes are
* Sequences are now encoded in u64, (as originally discussed in #46) . This implies the database format has changed and is also now more compact.
* Smafa now handles lowercase DNA sequences as well
* Slightly improved error message when a sequence cannot be encoded as DNA
* Smafa now verifies that sequences have the same length

Here is a benchmark of aligning 50,000 random DNA sequences against 1000 reference sequences:

Before
```
Benchmark 1: ./target/release/smafa query -q ~/Downloads/smafa/query.fna -d ~/Downloads/smafa/subject.fna.3cfb > /dev/null 2> /dev/null
  Time (mean ± σ):      6.944 s ±  0.069 s    [User: 6.884 s, System: 0.022 s]
  Range (min … max):    6.833 s …  7.010 s    5 runs
```

After:
```
Benchmark 1: ./target/release/smafa query -q ~/Downloads/smafa/query.fna -d ~/Downloads/smafa/subject.fna.0c41 > /dev/null 2> /dev/null
  Time (mean ± σ):     272.4 ms ±   1.3 ms    [User: 256.3 ms, System: 14.3 ms]
  Range (min … max):   271.1 ms … 274.5 ms    5 runs
```

Closes #46

### CODE REVIEW

**Comment by wwood** [comment]
Awesome, thanks. I'll review this altogether - might be most efficient if you request review when you think it's ready.

**Comment by jakobnissen** [comment]
It's done now. I can't request review since I'm not part of this repo, but you welcome to review it now

**Comment by wwood** [comment]
Hey, this looks awesome. I didn't realise that each bool was actually taking up 8 bits.

Right now you are only using 5 bits of each 8 though, right? I wonder if it could be pushed further, maybe using a bit field?

I'll do a proper review when I'm back in the office, but looks good so far.
Thanks again.

**Comment by jakobnissen** [comment]
Yeah, it currently uses 5 bits only.
We could make it even more dense by packing it into 4 or 3 bits, but I don't think this would be faster overall. Three bits is awkward because single nucleotides would cross the byte boudraries, making extracting and comparing single elements complicated.
Four bits works pretty well - this is the default representation of DNA and RNA in BioJulia, for example. Its 16 different values also allows the 15 UIPAC nucleotides plus a gap symbol. But, it complicates the comparisons in `get_distances` which dominate runtime. Now, the comparison can be done byte-wise, whereas if the symbols are compacted beyond one byte per symbol we'd have to do it in two passes - first masking out the four upper bits, then masking out the four lower bits.
I'm not certain this will be an overall benefit. Two passes will certainly require more compute, but on the other hand, most programs are bound by memory bandwidth and not CPU. So it could go either way, speed wise. My experience with BioJulia has been that the four-bit encoding does make it slower for most tasks.
Of course it'll reduce the memory consumption by 2x, but I don't get the feeling that smafa is memory constrained?

**Comment by wwood** [comment]
Hmm, I think what you are saying about the masking only applies if we are using `==` between the bases, correct? 

If we have a proper `xor` between an array of bits (as opposed to bools) then we shouldn't need to mask, we can just use `distance = sum(xor) / 2`. This was the original intention, but I had naively assumed that an array of bools would be implemented as an array of bits, not an array of bytes.

A way forward is to use this crate's method, which is apparently not in the official documentation, but supposedly actually works.
https://github.com/contain-rs/bit-vec/blob/master/src/lib.rs#L782

WDYT? There's other useful things in this PR of course, which are probably fine to merge, but I'd like your opinion first.

**Comment by jakobnissen** [comment]
That sounds like a good idea. I'm a little busy the next days, but at the end of the week I can look at it again.
We could pack 12 nucleotides in the 12*5=60 lower bits of each `u64`, then store the sequences as `Vec<u64>`.
This would allow us to use `u64::count_ones`, which is more efficient than doing that on smaller integers like u8.
We could of course pack the nucleotides densely, using all bits of the `u64`, but this is annoying to do and only gets a small density increase.

Some preliminary microbenchmarking in Julia says that is about 2x faster than what the code does now, so it might well be worth it!

**Comment by wwood** [comment]
Excellent - no rush!

**Comment by jakobnissen** [comment]
Okay, this is now ready for review (and merging).

Iadded more commits: 7c8eebd (and 0c41c62, to a smaller extent) improves performance, the two others are niceties.
My mini-benchmark is encouraging. Here, 50k queries against 1k references (on a different computer than my other timing):
3cfbe872: 6944 ms
6aa9092f: 1407 ms
0c41c628: 272 ms
So, 25x speedup! Not bad. Though of course this is with randomly generated sequences that may exhibit different behaviours than realistic sequences.

**Comment by wwood** [comment]
This seems pretty awesome, and so wil be a significant speedup for smafa and also SingleM. Nice. I would imagine that the fact they are random won't make any difference, but we'll see. I think aligning 1000 queries against 50k references would be more realistic, but no need to do further bunchmarking here.

I think everything seems good now, but it would probably be ideal if the behaviour was a bit nicer when the DB is in the old format. I'm happy to implement that but snowed under for a few days.

Is there some standard way of dealing with changing DB formats that you know of? Right now I was just thinking of attempting to deserialise with the newest format, and if that fails trying the old format. If the old one works then just error out with a helpful message - I don't think we need to maintain backwards compatibility.

Thanks, ben

**Comment by jakobnissen** [comment]
> Is there some standard way of dealing with changing DB formats that you know of?

The way I normally do it is to open the file, read the first few bytes to determine the database version and then use a match statement to pick the correct parser.

**Comment by wwood** [comment]
Thanks, done. I realised also that the version number wasn't updated in this PR. That's now done so the current DB version is now 2.

**Pull request merged**
